DROP ALL OBJECTS DELETE FILES;
CREATE TABLE usuario (
  ID BIGINT PRIMARY KEY,
  EMAIL VARCHAR(40),
  SENHA VARCHAR(20),
  USERNAME VARCHAR(40),
  SUPERUSUARIO VARCHAR(1)
);
CREATE TABLE PRODUTO (
  id BIGINT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  PRECO DECIMAL(10,2),
  TIPO CHAR(1),
  QUANTIDADE INT,
  ATIVO CHAR(1)
);


INSERT INTO USUARIO (ID,EMAIL,SENHA,USERNAME,SUPERUSUARIO) VALUES (1,'teste@gmail.com','exemplo123','joao','F');
INSERT INTO USUARIO (ID,EMAIL,SENHA,USERNAME,SUPERUSUARIO) VALUES (2,'super@gmail.com','exemplo123','maria','T');
INSERT INTO PRODUTO (id,NOME,DESCRICAO,PRECO,TIPO,QUANTIDADE,ATIVO) VALUES (1,'CAVALO','BRINQUEDO INFANTIL',3,'B',36,'T');
INSERT INTO PRODUTO (id,NOME,DESCRICAO,PRECO,TIPO,QUANTIDADE,ATIVO) VALUES (2,'CARRO','BRINQUEDO INFANTIL',8,'B',6,'T');
INSERT INTO PRODUTO (id,NOME,DESCRICAO,PRECO,TIPO,QUANTIDADE,ATIVO) VALUES (3,'MOTO','BRINQUEDO INFANTIL',22,'B',3,'T');
INSERT INTO PRODUTO (id,NOME,DESCRICAO,PRECO,TIPO,QUANTIDADE,ATIVO) VALUES (4,'AVIÃO','BRINQUEDO INFANTIL',33,'B',326,'F');